In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7970, 493, 331, 7847],
 [7970, 493, 331, 1512],
 [7970, 4951, 331, 5728],
 [4145, 3071, 5536, 7290, 4504],
 [4145, 3071, 5536, 7290, 9640],
 [3156, 7970, 2691, 331, 7560],
 [7219, 647, 9890, 7290]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7970  493  331 7847]
 [   0    0    0    0 7970  493  331 1512]
 [   0    0    0    0 7970 4951  331 5728]
 [   0    0    0 4145 3071 5536 7290 4504]
 [   0    0    0 4145 3071 5536 7290 9640]
 [   0    0    0 3156 7970 2691  331 7560]
 [   0    0    0    0 7219  647 9890 7290]]


In [8]:
## feature representation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 68ms/step


array([[[-0.00489031, -0.01453155,  0.01004475,  0.03501015,
          0.03688974,  0.04103038,  0.04947001, -0.02149772,
         -0.00180459,  0.0478004 ],
        [-0.00489031, -0.01453155,  0.01004475,  0.03501015,
          0.03688974,  0.04103038,  0.04947001, -0.02149772,
         -0.00180459,  0.0478004 ],
        [-0.00489031, -0.01453155,  0.01004475,  0.03501015,
          0.03688974,  0.04103038,  0.04947001, -0.02149772,
         -0.00180459,  0.0478004 ],
        [-0.00489031, -0.01453155,  0.01004475,  0.03501015,
          0.03688974,  0.04103038,  0.04947001, -0.02149772,
         -0.00180459,  0.0478004 ],
        [ 0.03243456,  0.01073186, -0.00404586,  0.0402161 ,
          0.02733291,  0.0160941 ,  0.0128857 ,  0.031857  ,
         -0.02233801,  0.01596048],
        [ 0.01252193,  0.03360662,  0.01277988,  0.01125895,
          0.04137144, -0.01732943,  0.04213597, -0.02974527,
         -0.01714069,  0.01390186],
        [-0.01137147, -0.03711289, -0.03352139, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 7970,  493,  331, 7847])

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[-0.00489031, -0.01453155,  0.01004475,  0.03501015,  0.03688974,
         0.04103038,  0.04947001, -0.02149772, -0.00180459,  0.0478004 ],
       [-0.00489031, -0.01453155,  0.01004475,  0.03501015,  0.03688974,
         0.04103038,  0.04947001, -0.02149772, -0.00180459,  0.0478004 ],
       [-0.00489031, -0.01453155,  0.01004475,  0.03501015,  0.03688974,
         0.04103038,  0.04947001, -0.02149772, -0.00180459,  0.0478004 ],
       [-0.00489031, -0.01453155,  0.01004475,  0.03501015,  0.03688974,
         0.04103038,  0.04947001, -0.02149772, -0.00180459,  0.0478004 ],
       [ 0.03243456,  0.01073186, -0.00404586,  0.0402161 ,  0.02733291,
         0.0160941 ,  0.0128857 ,  0.031857  , -0.02233801,  0.01596048],
       [ 0.01252193,  0.03360662,  0.01277988,  0.01125895,  0.04137144,
        -0.01732943,  0.04213597, -0.02974527, -0.01714069,  0.01390186],
       [-0.01137147, -0.03711289, -0.03352139, -0.01397002,  0.01558793,
         0.00041412, -0.02347815, -0.01575791